#Goal: Do the bottom up experiment -> Save the results in .RData format 
#Note: 1. The algorithms are written at the top of functions defined in functions.R 2. The plots and stats are shown in pwyResult.Rmd

#1. Use the original hclust tree 
#2. Use tree generated by gene ids in fig S1
#3. Use the tree generated for the conditions that are least correlated (Abs() of pcc was taken. 10 pairs of pcc were used)



#1. Use the original hclust tree 

##All above uses manual way to calculate. The following uses an automatic way by my newly defined function bottomUpExp()
input=ECK.Pathway_table[,c("ids","Pathway")]
input[,1]=as.numeric(input[,1]) ##Make the ids from "character" to "numeric"
input=input[input$Pathway!="Not in any pathway",] ##Remove genes not involved in any pathway
input=input[input[,2] %in% s1.pwy,] ##I want to only use pathways in fig s1 in Nichols' (They dropped the 1 gene and 2 gene pathways and the t-RNA charging pathway)
##Using %in% the order of the indices might mess up but that doens't affect the following experiment

##Do the experiment.(Takes about 4min)
##I want to only use pathways in s1.pwy

auto.pwyBottomUpExp=bottomUpExp(hclust_pcc_complete,input) ##Have to remove the duplicates and redo


###For those who have NoOfGenes=1 and fraction=NA and so on: Only 1 gene is found among all ECKs by using the 299 pathway names retrieved from Pathways.col 
###=> Can be verified by looking at EcoCycID.Pwys
###Updated: NoOfGenes=1 is filtered out in the function. Won't be calculated

###Be aware that in the experiment above duplicated strains were used

##The following requres results obtained from ADA and parse_random.results.R 

### Create a vecotor of corresponding negative control (fraction obtained by radom sampling). Bind to auto.pwyBottomUpExp
randomFraction=sapply(auto.pwyBottomUpExp$`No of Elements`,FUN=function(number){ #`No of Elements` is a partial match
  index=which(number==pwyBottomUpExp.random$avg.NoOfElements)
  return(pwyBottomUpExp.random$avg.avg.fraction[index])
})


auto.pwyBottomUpExp$randomFraction=randomFraction
save(auto.pwyBottomUpExp,file="Data/auto.pwyBottomUpExp.RData")


#2. Use tree generated by gene ids in fig S1

## Use the tree generated from gene ids in Fig.S1 to do the BottomUp experiment
## Generate hclust tree of only genes in pathways
figS1.pwy.genes=input #input was defined in this file previously. Only genes in fig.S1 were used
figS1.geneID=unique(figS1.pwy.genes$ids)
figS1.gene.hclust.quant=hclust(pcc_dist(All_Data[figS1.geneID,])) #"quant" means "quantitative fitness scores"
plot(figS1.gene.hclust.quant)

figS1genes.pwyBottomUpExp=bottomUpExp(figS1.gene.hclust.quant,figS1.pwy.genes) 

###Be aware that in the experiment above duplicated strains were used

##The following requres results obtained from ADA and parse_random.results.R 

### Create a vecotor of corresponding negative control (fraction obtained by radom sampling). Bind to auto.pwyBottomUpExp
randomFraction2=sapply(figS1genes.pwyBottomUpExp$`No of Elements`,FUN=function(number){
  index=which(number==pwyBottomUpExp.random$avg.NoOfElements)
  return(pwyBottomUpExp.random$avg.avg.fraction[index])
})


figS1genes.pwyBottomUpExp$randomFraction=randomFraction2
save(figS1genes.pwyBottomUpExp,file="Data/figS1genes.pwyBottomUpExp.RData")

#3. Use the tree generated by the conditions that are least correlated (Abs() of pcc was taken. 10 pairs of pcc were used)
input=ECK.Pathway_table[,c("ids","Pathway")]
input[,1]=as.numeric(input[,1]) ##Make the ids from "character" to "numeric"
input=input[input$Pathway!="Not in any pathway",] ##Remove genes not involved in any pathway
input=input[input[,2] %in% s1.pwy,] ##I want to only use pathways in fig s1 in Nichols' (They dropped the 1 gene and 2 gene pathways and the t-RNA charging pathway)
least10pcc.pwyBottomUpExp=bottomUpExp(least10pcc.hclust_pcc_complete,input) 

### Create a vecotor of corresponding negative control (fraction obtained by radom sampling). Bind to auto.pwyBottomUpExp
randomFraction3=sapply(least10pcc.pwyBottomUpExp$`No of Elements`,FUN=function(number){
  index=which(number==pwyBottomUpExp.random.least10pcc$avg.NoOfElements)
  return(pwyBottomUpExp.random.least10pcc$avg.avg.fraction[index])
})


least10pcc.pwyBottomUpExp$randomFraction=randomFraction3
save(least10pcc.pwyBottomUpExp,file="Data/least10pcc.pwyBottomUpExp.RData")

