#Goal: Do the bottom up experiment using protein complexes. The algorithms are written at the top of functions defined in functions.R
#1. Use the original hclust tree
#2. Use the tree generated by only the genes participated in the 196 protein complexes
#3. Use the tree generated for the conditions that are least correlated (Abs() of pcc was taken. 10 pairs of pcc were used)

# 1. Do the bottomUp exp. (No need to remove monomeric proteins becuase their results will be displayed with NA)
pcomplexBottomUpExp=bottomUpExp(hclust_pcc_complete,ids.originalName.pcomplex[,c(1,3)])

### Create a vecotor of corresponding negative control (fraction obtained by radom sampling). Bind to auto.pwyBottomUpExp
randomFraction=sapply(pcomplexBottomUpExp$`No of Elements`,FUN=function(number){
  index=which(number==pwyBottomUpExp.random$avg.NoOfElements) 
  ##The random results are the same as in pwyBottomUp. j=c(2,3,4,5,6,7,9,10,28) => a subset of pwy random. 
  ##There are no new numbers
  return(pwyBottomUpExp.random$avg.avg.fraction[index])
})


pcomplexBottomUpExp$randomFraction=randomFraction
save(pcomplexBottomUpExp,file="Data/pcomplexBottomUpExp.RData")


##The following is just for verification of having the right table:
###pcomplexes=table(X.Gene.products..complexes..polypeptides..and.RNAs..[X.Gene.products..complexes..polypeptides..and.RNAs..!=""]) 

###Verify that I got the right table
###sort(pcomplexes,decreasing = T)

###Exclude those monomers
###pcomplexes=pcomplexes[pcomplexes!=1]

###Verify that I got the right table
###sort(pcomplexes,decreasing = T)

detach(ECK.pcomplex)

#2. Use the tree generated by only the genes participated in the 196 protein complexes
pcomplexOnly.pcomplexBottomUpExp=bottomUpExp(pcomplex.hclust_pcc_complete,ids.originalName.pcomplex[,c(1,3)])

### Create a vecotor of corresponding negative control (fraction obtained by radom sampling). Bind to auto.pwyBottomUpExp
randomFraction2=sapply(pcomplexOnly.pcomplexBottomUpExp$`No of Elements`,FUN=function(number){
  index=which(number==pwyBottomUpExp.random$avg.NoOfElements) 
  ##The random results are the same as in pwyBottomUp. j=c(2,3,4,5,6,7,9,10,28) => a subset of pwy random. 
  ##There are no new numbers
  return(pwyBottomUpExp.random$avg.avg.fraction[index])
})

pcomplexOnly.pcomplexBottomUpExp$randomFraction=randomFraction2
save(pcomplexOnly.pcomplexBottomUpExp,file="Data/pcomplexOnly.pcomplexBottomUpExp.RData")


#3. Use the tree generated for the conditions that are least correlated (Abs() of pcc was taken. 10 pairs of pcc were used)
least10pcc.pcomplexBottomUpExp=bottomUpExp(least10pcc.hclust_pcc_complete,ids.originalName.pcomplex[,c(1,3)])

### Create a vecotor of corresponding negative control (fraction obtained by radom sampling). Bind to auto.pwyBottomUpExp
randomFraction3=sapply(least10pcc.pcomplexBottomUpExp$`No of Elements`,FUN=function(number){
  index=which(number==pwyBottomUpExp.random$avg.NoOfElements) 
  ##The random results are the same as in pwyBottomUp. j=c(2,3,4,5,6,7,9,10,28) => a subset of pwy random. 
  ##There are no new numbers
  return(pwyBottomUpExp.random$avg.avg.fraction[index])
})

least10pcc.pcomplexBottomUpExp$randomFraction=randomFraction3
save(least10pcc.pcomplexBottomUpExp,file="Data/least10pcc.pcomplexBottomUpExp.RData")